update=7/26/2017 12:39:54 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[pcbnew]
version=1
PageLayoutDescrFile=SchematicLayout.kicad_wks
LastNetListRead=fk-core.net
PadDrill=0
PadDrillOvalY=0
PadSizeH=0.75
PadSizeV=0.75
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=0.7999999999999999
ModuleTextSizeH=0.7999999999999999
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.1016
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[schematic_editor]
version=1
PageLayoutDescrFile=SchematicLayout.kicad_wks
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
ERC_TestSimilarLabels=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=fk-weather-rescue
LibName2=D:/Life/conservify/kicad/conservify
LibName3=D:/Life/conservify/RocketScreamKicadLibrary/RocketScreamKicadLibrary
LibName4=C:/Program Files/KiCad/share/kicad/library/conn
LibName5=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName6=C:/Program Files/KiCad/share/kicad/library/74xx
LibName7=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName8=C:/Program Files/KiCad/share/kicad/library/actel
LibName9=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName10=C:/Program Files/KiCad/share/kicad/library/allegro
LibName11=C:/Program Files/KiCad/share/kicad/library/Altera
LibName12=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName13=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName14=C:/Program Files/KiCad/share/kicad/library/atmel
LibName15=C:/Program Files/KiCad/share/kicad/library/audio
LibName16=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName17=C:/Program Files/KiCad/share/kicad/library/bbd
LibName18=C:/Program Files/KiCad/share/kicad/library/bosch
LibName19=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName20=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName21=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName22=C:/Program Files/KiCad/share/kicad/library/contrib
LibName23=C:/Program Files/KiCad/share/kicad/library/cypress
LibName24=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName25=C:/Program Files/KiCad/share/kicad/library/device
LibName26=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName27=C:/Program Files/KiCad/share/kicad/library/diode
LibName28=C:/Program Files/KiCad/share/kicad/library/display
LibName29=C:/Program Files/KiCad/share/kicad/library/dsp
LibName30=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName31=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName32=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName33=C:/Program Files/KiCad/share/kicad/library/gennum
LibName34=C:/Program Files/KiCad/share/kicad/library/graphic
LibName35=C:/Program Files/KiCad/share/kicad/library/hc11
LibName36=C:/Program Files/KiCad/share/kicad/library/intel
LibName37=C:/Program Files/KiCad/share/kicad/library/interface
LibName38=C:/Program Files/KiCad/share/kicad/library/ir
LibName39=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName40=C:/Program Files/KiCad/share/kicad/library/leds
LibName41=C:/Program Files/KiCad/share/kicad/library/linear
LibName42=C:/Program Files/KiCad/share/kicad/library/logo
LibName43=C:/Program Files/KiCad/share/kicad/library/maxim
LibName44=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName45=C:/Program Files/KiCad/share/kicad/library/memory
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName55=C:/Program Files/KiCad/share/kicad/library/modules
LibName56=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName57=C:/Program Files/KiCad/share/kicad/library/motorola
LibName58=C:/Program Files/KiCad/share/kicad/library/motors
LibName59=C:/Program Files/KiCad/share/kicad/library/msp430
LibName60=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName61=C:/Program Files/KiCad/share/kicad/library/nxp
LibName62=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName63=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName64=C:/Program Files/KiCad/share/kicad/library/opto
LibName65=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName66=C:/Program Files/KiCad/share/kicad/library/philips
LibName67=C:/Program Files/KiCad/share/kicad/library/power
LibName68=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName69=C:/Program Files/KiCad/share/kicad/library/powerint
LibName70=C:/Program Files/KiCad/share/kicad/library/pspice
LibName71=C:/Program Files/KiCad/share/kicad/library/references
LibName72=C:/Program Files/KiCad/share/kicad/library/regul
LibName73=C:/Program Files/KiCad/share/kicad/library/relays
LibName74=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName75=C:/Program Files/KiCad/share/kicad/library/sensors
LibName76=C:/Program Files/KiCad/share/kicad/library/silabs
LibName77=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName78=C:/Program Files/KiCad/share/kicad/library/stm8
LibName79=C:/Program Files/KiCad/share/kicad/library/stm32
LibName80=C:/Program Files/KiCad/share/kicad/library/supertex
LibName81=C:/Program Files/KiCad/share/kicad/library/switches
LibName82=C:/Program Files/KiCad/share/kicad/library/texas
LibName83=C:/Program Files/KiCad/share/kicad/library/transf
LibName84=C:/Program Files/KiCad/share/kicad/library/transistors
LibName85=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName86=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName87=C:/Program Files/KiCad/share/kicad/library/valves
LibName88=C:/Program Files/KiCad/share/kicad/library/video
LibName89=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName90=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName91=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName92=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName93=C:/Program Files/KiCad/share/kicad/library/zetex
LibName94=C:/Program Files/KiCad/share/kicad/library/Zilog
